#!/usr/bin/env python

import argparse
from http.server import HTTPServer, SimpleHTTPRequestHandler


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--static_folder_path', default='../../deployments/web_shell/static')
    parser.add_argument('--port', default=8100, type=int)
    args = parser.parse_args()
    static_folder_path = args.static_folder_path
    port = args.port

    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=static_folder_path, **kwargs)

    httpd = HTTPServer(('localhost', port), Handler)
    print('Initialized server')

    httpd.serve_forever()


if __name__ == '__main__':
    if main():
        print('Build process failed.')
