ALIGNMENT_GRID_UNIT = 10
AGU = ALIGNMENT_GRID_UNIT

DEFAULT_NOTE_WIDTH = 32 * AGU
DEFAULT_NOTE_HEIGHT = 16 * AGU
MIN_NOTE_WIDTH = 3 * AGU
MIN_NOTE_HEIGHT = 3 * AGU
MAX_NOTE_WIDTH = 192 * AGU
MAX_NOTE_HEIGHT = 192 * AGU

DEFAULT_BG_COLOR_ROLE = "primary"
DEFAULT_COLOR_ROLE = "onPrimary"

DEFAULT_ARROW_THICKNESS = 1.5

# Kept for convert_misli_archives/visualizer.py
DEFAULT_EYE_HEIGHT = 40

LOCAL_USER_ID = "local"
DEFAULT_PROJECT_ID = "notebook"
DEFAULT_PROJECT_TITLE = "Notebook"
