#!/usr/bin/env python3
import os
import subprocess
import argparse


def main():
    parser = argparse.ArgumentParser(
        description='Traverses all project folders and invokes'
                    '"pip install -e" on them to do a dev install.')
    parser.parse_args()

    project_folder = os.path.dirname(os.path.realpath(__file__))
    print('Running dev install for project Misli in folder', project_folder)

    successful_install_folders = []
    unsuccessful_install_folders = []
    for root, dirs, files in os.walk(project_folder):
        if 'setup.py' not in files:
            continue

        command = ['pip', 'install', '-e', root]
        print('Invoking %s' % command)
        result = subprocess.run(command)

        if not result.returncode:
            successful_install_folders.append(root)
        else:
            unsuccessful_install_folders.append(root)

    if successful_install_folders:
        print('\nInstallation successful for these folders:')

        for f in successful_install_folders:
            print(f)

    if unsuccessful_install_folders:
        print('\nInstallation did not succeed in these folders:')

        for f in unsuccessful_install_folders:
            print(f)


if __name__ == '__main__':
    main()
