import os
from misli_debug import LoggingLevels

log_lvl_name = os.environ.get('MISLI_LOGGING_LEVEL', LoggingLevels.ERROR.name)
LOGGING_LEVEL = LoggingLevels[log_lvl_name].value

MAX_RENDER_TIME = 0.017  # (s) ~60 fps
NOTE_MARGIN = 5

MOVE_SPEED = 1

INITIAL_EYE_Z = 40

MIN_HEIGHT_SCALE = 0.2
MAX_HEIGHT_SCALE = 200

NO_SCALE_LINE_SPACING = 20

FONT_SIZE_IN_PX = 12

DEFAULT_NOTE_WIDTH = 320
DEFAULT_NOTE_HEIGHT = 160
MIN_NOTE_WIDTH = 30
MIN_NOTE_HEIGHT = 30
MAX_NOTE_WIDTH = 1920
MAX_NOTE_HEIGHT = 1280

DEFAULT_BG_COLOR = [0, 0, 1, 0.1]
DEFAULT_COLOR = [0, 0, 1, 1]

RESIZE_CIRCLE_RADIUS = 20

ALIGNMENT_GRID_UNIT = 10

ORGANISATION_NAME = 'p10'
DESKTOP_APP_NAME = 'misli'
DESKTOP_APP_VERSION = '4.0.0'
